AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy services to AWS'

Resources:

  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: software-programming-quiz-lambda-bucket

  SendEmailLambda:
    Type:  AWS::Lambda::Function
    Properties: 
      FunctionName: send-email-lambda
      Runtime: python3.9
      Role: arn:aws:iam::185080013142:role/lambda-role
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: software-programming-quiz-lambda-bucket
        S3Key: send-email-lambda.zip

  CreateUserLambda:
    Type:  AWS::Lambda::Function
    Properties: 
      FunctionName: create-user-lambda
      Runtime: python3.9
      Role: arn:aws:iam::185080013142:role/lambda-role
      Handler: lambda_function.lambda_handler
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            return None

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: software-programming-quiz-users
      AutoVerifiedAttributes:
        - email
      UsernameAttributes: 
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: organization
          AttributeDataType: String
          Mutable: false
          Required: false

  Database:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Engine: mysql
      DBName: software_quiz
      PubliclyAccessible: True
      MasterUsername: admin
      MasterUserPassword: password1