import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Profile.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Profile Page
        </h1>

        <p className={styles.description}>
          This is where the user will see profile information along with the a list of quizzes they have created and a button to create new quizzes.
        </p>

      </main>

    </div>
  )
}
