import Head from 'next/head'
import React from 'react'
import {useState} from 'react'
import Image from 'next/image'
import styles from '../styles/Signup.module.css'
import axios from 'axios'

export default function Home() {
    const [firstName, setFirstName] = useState('')
    const [lastName, setLastName] = React.useState('enter last name')
    const [email, setEmail] = React.useState('enter email address')
    const [company, setCompany] = React.useState('enter company name')
    const sendDataToApi = async () => {
       let response = await axios.post('/api/create-user', {firstName, lastName, company, email})
    }
const submit = (e) => {
e.preventDefault()
sendDataToApi()
}

 // create a form on this page, and when complete (on button click) send data to the 'api' rout
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sign up page
        </h1>

        <p className={styles.description}>
          This is where the user will sign up for a profile by submitting their information.

        </p>
        <form onSubmit={submit}>
        <input value={firstName} placeholder="First Name"onChange={e=>setFirstName(e.target.value)} />
        <input value={lastName} placeholder="Last Name" onChange={e=>setLastName(e.target.value)} />
        <input value={company} placeholder="Company Name" onChange={e=>setCompany(e.target.value)} />
        <input value={email} onChange={e=>setEmail(e.target.value)} />
        <button type="submit">submit</button>
        </form>

      </main>

    </div>
  )
}
