import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Signup.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sign up page
        </h1>

        <p className={styles.description}>
          This is where the user will sign up for a profile by submitting their information. 
        </p>

      </main>

    </div>
  )
}
