# This will zip and upload lambda code to S3 buckets
name: Deploy Lambdas

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.9' 

    - name: Install Python requirements
      run: |
        cd lambdas/create-quiz-lambda
        python -m pip install --target ./packages -r requirements.txt 
        cd ..
        cd quiz-invite-lambda
        python -m pip install --target ./packages -r requirements.txt 

    - name: Zip files
      run: |
        cd lambdas/quiz-invite-lambda
        zip ../quiz-invite-lambda.zip lambda_function.py
        cd packages
        zip -r ../../quiz-invite-lambda.zip .
        cd ../../../
        cd lambdas/create-user-lambda
        zip ../create-user-lambda.zip lambda_function.py
        cd ../../
        cd lambdas/create-quiz-lambda
        zip ../create-quiz-lambda.zip lambda_function.py
        cd packages
        zip -r ../../create-quiz-lambda.zip .
        cd ../../../
        cd lambdas/get-quizzes-lambda
        zip ../get-quizzes-lambda.zip lambda_function.py
        cd packages
        zip -r ../../get-quizzes-lambda.zip .
        cd ../../../

    - name: Deploy to S3 and update source
      run: |
        aws s3 cp lambdas/quiz-invite-lambda.zip s3://software-programming-quiz-lambda-bucket
        aws lambda update-function-code --function-name quiz-invite-lambda --s3-bucket software-programming-quiz-lambda-bucket --s3-key quiz-invite-lambda.zip
        aws s3 cp lambdas/create-user-lambda.zip s3://software-programming-quiz-lambda-bucket
        aws lambda update-function-code --function-name create-user-lambda --s3-bucket software-programming-quiz-lambda-bucket --s3-key create-user-lambda.zip
        aws s3 cp lambdas/create-quiz-lambda.zip s3://software-programming-quiz-lambda-bucket
        aws lambda update-function-code --function-name create-quiz-lambda --s3-bucket software-programming-quiz-lambda-bucket --s3-key create-quiz-lambda.zip
        aws s3 cp lambdas/get-quizzes-lambda.zip s3://software-programming-quiz-lambda-bucket