# This will deploy the cloudformation template to create resources in AWS
name: Deploy Cloudformation

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    - name: Deploy to Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: software-programming-quiz-stack
        template: cloudformation/resources.yaml