# This will zip and upload lambda code to S3 buckets
name: Deploy Lambdas

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Zip files
      run: |
        zip lambdas/send-email-lambda.zip lambdas/send-email-lambda/lambda_function.py

    - name: Deploy to S3
      run: aws s3 cp lambdas/send-email-lambda.zip s3://software-programming-quiz-lambda-bucket